version: "3"
services:
  web:
    image: koala944/accountant:webapp
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.4"
          memory: 512M
      restart_policy:
        condition: on-failure
    ports:
      - "4040:8080"
    networks:
      - accountant_net
  loggingdb:
    image: koala944/accountant:loggingdb
    environment:
      MYSQL_ROOT_PASSWORD: Pass1234 
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure
    ports:
      - "3307:3306"
    networks:
      - accountant_net
  mqserver:
    image: rabbitmq:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.4"
          memory: 1024M
      restart_policy:
          condition: on-failure
    networks:
      - accountant_net  
  loggingdal:
    image: koala944/accountant:logging-dal
    depends_on:
      - mqserver
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.4"
          memory: 512M
      restart_policy:
          condition: on-failure
    networks:
      - accountant_net  
networks:
  accountant_net: